/*
 * generated by Xtext
 */
package de.wwu.pi.acse.customerDsl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class CustomerDslUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return de.wwu.pi.acse.customerDsl.ui.internal.CustomerDslActivator.getInstance().getInjector("de.wwu.pi.acse.customerDsl.CustomerDsl");
	}
	
}
