/*
 * generated by Xtext
 */
package de.wwu.pi.acse.customerDsl.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractCustomerDslValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(de.wwu.pi.acse.customerDsl.customerDsl.CustomerDslPackage.eINSTANCE);
		return result;
	}
}
