/*
 * generated by Xtext
 */
package de.wwu.pi.acse.customerDsl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class CustomerDslStandaloneSetup extends CustomerDslStandaloneSetupGenerated{

	public static void doSetup() {
		new CustomerDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

