/*
 * generated by Xtext
 */
package de.wwu.pi.acse.customerDsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class CustomerDslRuntimeModule extends de.wwu.pi.acse.customerDsl.AbstractCustomerDslRuntimeModule {

}
