/*
 * generated by Xtext
 */
package de.wwu.pi.acse.customerDsl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import de.wwu.pi.acse.customerDsl.ui.internal.CustomerDslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class CustomerDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return CustomerDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return CustomerDslActivator.getInstance().getInjector(CustomerDslActivator.DE_WWU_PI_ACSE_CUSTOMERDSL_CUSTOMERDSL);
	}
	
}
