/*
 * generated by Xtext
 */
package de.wwu.pi.acse.customerDsl.validation

import org.eclipse.xtext.validation.Check
import de.wwu.pi.acse.customerDsl.customerDsl.Address
import de.wwu.pi.acse.customerDsl.customerDsl.CustomerDslPackage

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class CustomerDslValidator extends AbstractCustomerDslValidator {

	@Check
	def checkAddressValidZipCode(Address address) {
		if(!address.getZip().matches("[0-9]{5}(-[0-9]{4})?"))
			warning("Invalid ZIP code, should be '12345' or '12345-6789'", 
					CustomerDslPackage.Literals.ADDRESS__ZIP);
	}
}
