/*
 * generated by Xtext
 */
package de.wwu.pi.acse.customerDsl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import de.wwu.pi.acse.customerDsl.services.CustomerDslGrammarAccess;

public class CustomerDslParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private CustomerDslGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected de.wwu.pi.acse.customerDsl.parser.antlr.internal.InternalCustomerDslParser createParser(XtextTokenStream stream) {
		return new de.wwu.pi.acse.customerDsl.parser.antlr.internal.InternalCustomerDslParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "CustomerDb";
	}
	
	public CustomerDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(CustomerDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
