/*
 * generated by Xtext
 */
package de.wwu.pi.acse.customerDsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class CustomerDslUiModule extends de.wwu.pi.acse.customerDsl.ui.AbstractCustomerDslUiModule {
	public CustomerDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
