/*
 * generated by Xtext
 */
package de.wwu.pi.acse.customerDsl.ui.contentassist

import de.wwu.pi.acse.customerDsl.ui.contentassist.AbstractCustomerDslProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class CustomerDslProposalProvider extends AbstractCustomerDslProposalProvider {
}
